" Maintainer:	Konstantin Milchev <konstantin.milchev@gmail.com>
" Last change:	2023 January 4  
set nocompatible
filetype off

"Defaults to ~/vimrc/plugged
call plug#begin()


Plug 'https://github.com/preservim/nerdtree.git'
Plug 'https://github.com/tpope/vim-surround.git'
Plug 'https://github.com/morhetz/gruvbox.git'
Plug 'https://github.com/dhruvasagar/vim-table-mode.git'
Plug 'instant-markdown/vim-instant-markdown', {'for': 'markdown', 'do': 'yarn install'}

call plug#end()

filetype plugin indent on
syntax enable
set nomore
set noswapfile

" set vim font
"set guifont=Consolas:h10 (Stopped using November 2022)
set guifont=Roboto_Mono_Light:h16:W300:cANSI:qDRAFT

" set window size 
set lines=35 columns=125

" set window size 
winpos 1250 700

" set noundo filetype
"set noundofile

" syntax 
syntax on

" Buffers
"Move to the previous buffer with "gp"
nnoremap gp :bp<CR>
" Move to the next buffer with "gn"
nnoremap gn :bn<CR>
" List all possible buffers with "gl"
nnoremap gl :ls<CR>
" List all possible buffers with "gb" and accept a new buffer argument [1]
nnoremap gb :ls<CR>:b
" Unbind Escape Key in insert mode. Bind 'jk' or 'kj'.

" Mappings

" non-compatible mode
"set nocp

" NERDTree
" autocmd vimenter * NERDTree
nmap <F6> :NERDTreeToggle<CR>

"filetype plugin on
"Uncomment to override defaults:
"let g:instant_markdown_open_to_the_world = 1
"let g:instant_markdown_slow = 1
let g:instant_markdown_autostart = 1
"let g:instant_markdown_allow_unsafe_content = 1
"let g:instant_markdown_allow_external_content = 0
"let g:instant_markdown_mathjax = 1
"let g:instant_markdown_mermaid = 1
"let g:instant_markdown_logfile ='~\vimfiles\logs\instant-markdown.log' 
"let g:instant_markdown_autoscroll = 0
"let g:instant_markdown_port = 8090
"let g:instant_markdown_python = 1
"
set colorcolumn=160 number

 "Example: To display images automatically on buffer write.
" let vim_markdown_preview_toggle=2
" let vim_markdown_preview_browser='Google Chrome'

" Color Scheme
colorscheme gruvbox


"Mappings
ino <esc> <nop>
ino jk <esc>:w<cr>
ino kj <esc>:w<cr>


" Functions 
