" Maintainer:	Konstantin Milchev <konstantin.milchev@gmail.com>
" Last change:	2023 March 7

"Greet
"echo "Use now, configure later (>^.^<)"

"The space between the left numbers and the left boarder
set numberwidth=4

set nocompatible
filetype off

"Defaults to ~/vimrc/plugged
call plug#begin()


Plug 'https://github.com/preservim/nerdtree.git'
Plug 'https://github.com/tpope/vim-surround.git'
Plug 'https://github.com/morhetz/gruvbox.git'
Plug 'https://github.com/dhruvasagar/vim-table-mode.git'
Plug 'instant-markdown/vim-instant-markdown', {'for': 'markdown', 'do': 'yarn install'}
Plug 'sheerun/vim-polyglot'
Plug 'dense-analysis/ale'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }

call plug#end()

filetype plugin indent on
syntax enable
set nomore
set noswapfile

" set vim font
set guifont=Roboto_Mono_Light:h16:W300:cANSI:qDRAFT

" set window size 
set lines=35 columns=125

" set window position
winpos 1250 700

" syntax 
syntax on


" NERDTree
autocmd vimenter * NERDTree
nmap <leader>nt :NERDTreeToggle<CR>

" Artistic Style 
autocmd BufNewFile,BufRead *.cs set formatprg=astyle\ -A1Txe 

" On entering a buffer change the working directory to the file where it's
" located
autocmd BufEnter * silent! lcd %:p:h

" Color Scheme
colorscheme gruvbox
set colorcolumn=160 number


""Mappings


" use jk and kj to save a file in insert mode
ino jk <esc>:w<cr>
ino kj <esc>:w<cr>

" Unmap esc in insert mode, nop is no operation
ino <esc> <nop>

"map leader
let mapleader = ","

"Open vimrc in normal mode with leader ev
nnoremap <leader>ev :split $MYVIMRC<cr>

"Refresh vimrc in normal mode with leader sv
nnoremap <leader>sv :source $MYVIMRC<cr>

map <leader>te :term ++close<cr>
map / /\c

nno ls :FZF <CR>

" Buffers
"Move to the previous buffer with "gp"
nnoremap gp :bp<CR>
" Move to the next buffer with "gn"
nnoremap gn :bn<CR>
" List all possible buffers with "gl"
nnoremap gl :ls<CR>
" List all possible buffers with "gb" and accept a new buffer argument [1]

nnoremap gb :ls<CR>:b

""Abbreviations

iabbrev esle else

""Commands
:command Gr cd ~/source/repos/
"Command-T
 let g:CommandTPreferredImplementation='ruby'

